name: Feature Branch Sync Check

on:
  pull_request:
    branches:
      - Release

jobs:
  check_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Latest Changes
        run: git fetch

      - name: Compare with Dev Branch
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          if git merge-base --is-ancestor ${{ github.event.pull_request.head.ref }} origin/develop; then
            echo "Feature branch is up to date with the dev branch."
          else
            git merge-base --is-ancestor ${{ github.event.pull_request.head.ref }} $(git rev-parse ${{ github.event.pull_request.head.ref }})..origin/develop
            sync_check_result=$?
            if [ $sync_check_result -eq 0 ]; then
              echo "Feature branch is up to date with the squashed commits on the dev branch."
            else
              echo "Feature branch is not up to date with the dev branch or the squashed commits on the dev branch."
              exit 1
            fi
          fi

