on:
  push:
    branches:
      - dev/dev-shrek
      - dev/dev-vikings
      
jobs:
   backup:
    name: Backup ${{ github.head_ref || github.ref_name }} 
    environment: Dev-shrek
    runs-on: ubuntu-latest
    steps:
      - run:  |
          echo Hello from common workflow
  
