on:
  push:
    branches:
      - dev/dev-shrek
      - dev/dev-vikings
env:
  teams: '["shrek", "vikings"]'
      
jobs:
   backup:
    name: Backup ${{ github.head_ref  }}
    runs-on: ubuntu-latest
    steps:
      - name: branch name is ${{ github.ref_name  }} 
        run:  |
          echo Hello from common workflow
          echo $teams[0]
          echo env.teams[0]
          echo ${{ env.teams[0] }}
  
