name: CI +  CD

on:
  push:
    branches: [ Release ]
  pull_request:
    branches: [ Release ]
  workflow_dispatch:

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  setup-env:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      depEnv: ${{ steps.step1.outputs.depEnv }}
      envUrl: ${{ steps.step1.outputs.envUrl }}
    steps:
      - id: step1
        run: |
          if [ "${{ github.head_ref }}" == "dev/dev-arizona" ]
          then
            echo "depEnv=dev-arizona" >> $GITHUB_OUTPUT
            echo "envUrl=https://dev-arizona.example.com" >> $GITHUB_OUTPUT
          else [ "${{ github.head_ref }}" == "dev/dev-banglore" ]
            echo "depEnv=dev-banglore" >> $GITHUB_OUTPUT
            echo "envUrl=https://dev-banglore.example.com" >> $GITHUB_OUTPUT
          fi
      
  Build:
    needs: [setup-env]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile and buil
        run: echo build completed
          
  dump_contexts_to_log:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        
  DeployDev:
    name: Deploy to Dev ${{needs.setup-env.outputs.depEnv}}
    needs: [Build,setup-env]
    if: github.event_name == 'pull_request' && github.head_ref == 'dev/dev-arizona' || github.head_ref == 'dev/dev-banglore' || github.head_ref == 'dev/dev-california'
    runs-on: ubuntu-latest
    environment: 
      name: ${{needs.setup-env.outputs.depEnv}}
      url: '${{ needs.setup-env.outputs.envUrl }}'
    steps:
      - name: Deploy to ${{ github.event.repository.name }}
        run: |
          echo ${{needs.setup-env.outputs.depEnv}}
          echo deployment completed
    
  DeployStaging:
    name: Deploy to QA1 
    if: github.event_name == 'pull_request' && github.base_ref == 'Release'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: qa1
      url: ${{ env.DEMO_URL }}
    steps:
      - name: Deploy
        run: echo I am deploying! 

  DeployProd:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
