name: CI + CD

on:
  push:
    branches: [ Release ]
  pull_request:
    branches: [ Release ]
  workflow_dispatch:

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world! github ref is $GITHUB_REF and event ref ${{ github.ref }} and ${{ github.base_ref}} end
    
  DeployDev:
    name: Deploy to Dev ${{ github.head_ref }}
    if: github.event_name == 'pull_request' && github.head_ref == 'dev/dev-arizona' || github.head_ref == 'dev/dev-banglore' || github.head_ref == 'dev/dev-california' 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.head_ref }}
      url: '$NODE_ENV'
    steps:
      - name: Deploy
        run: | 
          echo I am deploying! "$NODE_ENV" > test.txt
          cat test.txt
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
