name: CI +  CD

on:
  push:
    branches: [ Release ]
  pull_request:
    branches: [ Release ]
  workflow_dispatch:

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}
  REPO_NAME: ${{ github.event.repository.name }}
  DEMO_URL: 'http://test.myapp.com'

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      devEnv: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2
        id: step1
      - name: Compile
        run: echo Hello, world! github ref is $GITHUB_REF and event ref ${{ github.ref }} and ${{ github.base_ref}} end
        
      - name: Set env variables
        id: buildnumber
        if: github.head_ref == 'dev/dev-arizona'
        env: 
          DEV_URL : https://dev1.test.com
        run: |
          if [ "${{ github.head_ref }}" == "refs/heads/dev/dev-arizona" ]; then
            echo "::set-env name=MY_VARIABLE::dev1.example.com"
          elif [ "${{ github.head_ref }}" == "refs/heads/dev/dev-banglore" ]; then
            echo "::set-env name=MY_VARIABLE::dev2.example.com"
          fi
          echo "::set-output name=test::hello"
          echo "{test}={hello}" >> $GITHUB_OUTPUT
          echo ${{ env.MY_VARIABLE }}
          echo '${{ env.MY_VARIABLE }}'
          echo ${{ env.DEV_URL }}
       
      - name: Set env variables for dev-banglore
        if: github.head_ref == 'dev/dev-banglore'
        env: 
          DEV_URL : https://dev2.test.com
        run: |
          echo ${{ env.DEV_URL }}
          echo "::set-output name=test::world"
      
      - name: print common variable
        run: |
          echo ${{ env.DEV_URL }}
          echo $GITHUB_ENV
          echo ${{ needs.build.outputs.devEnv }}
      
        
          
          
  dump_contexts_to_log:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  DeployDev:
    name: Deploy to Dev
    if: github.event_name == 'pull_request' && github.head_ref == 'dev/dev-arizona' || github.head_ref == 'dev/dev-banglore' || github.head_ref == 'dev/dev-california' 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.head_ref }}
      url: '${{ env.MY_ENV_VAR }}'
    steps:
      - name: Deploy to ${{ github.event.repository.name }}
        run: |
          echo $REPO_NAME/api
          echo $DEV_URL
          echo "${{ env.MY_VARIABLE }}"
          echo ${{ env.MY_ENV_VAR }}
          echo ${{ env.DEV_URL }}
          echo "${{ steps.buildnumber.outputs.TEST_URL }}"
          
          
    
  DeployStaging:
    name: Deploy to QA1 
    if: github.event_name == 'pull_request' && github.base_ref == 'Release'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: qa1
      url: ${{ env.DEMO_URL }}
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
