name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world! github ref is $GITHUB_REF and event ref ${{ github.ref }} and ${{ github.base_ref}} end
    
  DeployDev1014:
    name: Deploy to Dev 
    if: github.event_name == 'pull_request' && github.head_ref == 'dev/dev-GDT1014' || github.head_ref == 'dev/dev-GDT1017'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.head_ref }}
      url: 'http://dev1014.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
  DeployDev1015:
    name: Deploy to Dev 1015 
    if: github.event_name == 'pull_request' && github.head_ref == 'dev/dev-GDT1015'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://dev1015.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying to 1015
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: 'http://test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 
    
