name: Testing workflow dispatch input

on:
  workflow_dispatch:
    inputs:
      vmRepo:
        description: Choose a source SiteRx Repo to checkout.
        type: choice
        options:
         - FRONTEND
         - siterx-referral-console
         - siterx-annotator
         - siterx-trial-site-console
         - siterx-site-console
         - siterx-super-admin
         - siterx-payments
         - siterx-shorty-console
         - BACKEND
         - siterx-webapp
         - siterx-shorty-backend
         - siterx-ehr-patient-extractor
         - siterx-encryption-service
         - siterx-document-handler
         - siterx-ehr-patient-rpt-upload
      action:
        description: Choose an action to perform
        type: choice
        default: build
        options:
         - Build
         - Deploy
         - Delete
jobs:
  setup:
    env: 
      frontend : '["siterx-referral-console","siterx-annotator","siterx-trial-site-console"]'
      backend : '["siterx-webapp", "siterx-shorty-backend"]'
      repo: devops
      branch: dev
      InpRepoName: ${{ github.event.inputs.vmRepo }}
      FrontendRepoName: 'siterx-annotator'
      BackendRepoName: 'siterx-shorty-backend'
      
    name: Conditionally Run
    runs-on: ubuntu-latest
    steps:
      #!
      - if: contains(env.frontend, env.FrontendRepoName)
        run: echo $FrontendRepoName is frontend $InpRepoName
      - if: contains(env.backend, env.FrontendRepoName)
        run: echo $FrontendRepoName is backend $InpRepoName
        
      - if: contains(env.frontend, env.BackendRepoName)
        run: echo $BackendRepoName is frontend $InpRepoName
      - if: contains(env.backend, env.BackendRepoName)
        run: echo $BackendRepoName is backend
        
      - if: contains(env.frontend, env.InpRepoName)
        run: echo $InpRepoName is frontend
      - if: contains(env.backend, env.InpRepoName)
        run: echo $InpRepoName is backend
      
      
      
