name: Testing workflow dispatch input

on:
  workflow_dispatch:
    inputs:
      vmRepo:
        description: Choose a source SiteRx Repo to checkout.
        type: choice
        options:
         - FRONTEND
         - siterx-referral-console
         - siterx-annotator
         - siterx-trial-site-console
         - siterx-site-console
         - siterx-super-admin
         - siterx-payments
         - siterx-shorty-console
         - BACKEND
         - siterx-webapp
         - siterx-shorty-backend
         - siterx-ehr-patient-extractor
         - siterx-encryption-service
         - siterx-document-handler
         - siterx-ehr-patient-rpt-upload
      action:
        description: Choose an action to perform
        type: choice
        default: build
        options:
         - Build
         - Deploy
         - Delete
jobs:
  setup:
    env: 
      frontend : '["siterx-referral-console","siterx-annotator","siterx-trial-site-console"]'
      backend : '["siterx-webapp", "siterx-shorty-console"]'
      repo: devops
      branch: dev
      InpRepoName: format(${{ github.event.inputs.vmRepo }})
      
    name: Conditionally Run
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.vmRepo }} $InpRepoName
      - if:   contains(env.frontend, format(${{ github.event.inputs.vmRepo }}))
        run:  echo format(${{ github.event.inputs.vmRepo }}) "is frontend"
      - if:   contains(env.frontend, env.InpRepoName)
        run:  echo $InpRepoName "is frontend"
      - if:   contains(env.frontend, $InpRepoName)
        run:  echo $InpRepoName "is frontend"
        
      - if: contains(env.backend, $InpRepoName)
        run: echo "$InpRepoName is a backend app"
        
      - if:   contains(env.backend, env.InpRepoName)
        run:  echo $InpRepoName "is backen"
