name: Testing workflow dispatch input

on:
  workflow_dispatch:
    inputs:
      vmRepo:
        description: Choose a source SiteRx Repo to checkout.
        type: choice
        options:
         - FRONTEND
         - siterx-referral-console
         - siterx-annotator
         - siterx-trial-site-console
         - siterx-site-console
         - siterx-super-admin
         - siterx-payments
         - siterx-shorty-console
         - BACKEND
         - siterx-webapp
         - siterx-shorty-backend
         - siterx-ehr-patient-extractor
         - siterx-encryption-service
         - siterx-document-handler
         - siterx-ehr-patient-rpt-upload
      action:
        description: Choose an action to perform
        type: choice
        default: build
        options:
         - Build
         - Deploy
         - Delete
jobs:
  setup:
    env: 
      frontend : '["siterx-referral-console","siterx-annotator","siterx-trial-site-console"]'
      backend : '["siterx-webapp", "siterx-shorty-console"]'
      repo: devops
      branch: dev
      
    name: Conditionally Run
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.events.env.frontend }}
      - if:   contains(env.frontend, 'siterx-webapp')
        run:  echo 'siterx-webapp' is frontend
      - if: contains(env.backend, 'siterx-webapp')
        run: echo 'siterx-webapp' is a backend app
  
