name: Testing workflow dispatch input

on:
  workflow_dispatch:
    inputs:
      vmRepo:
        description: Choose a source SiteRx Repo to checkout.
        type: choice
        options:
         - FRONTEND
         - siterx-referral-console
         - siterx-annotator
         - siterx-trial-site-console
         - siterx-site-console
         - siterx-super-admin
         - siterx-payments
         - siterx-shorty-console
         - BACKEND
         - siterx-webapp
         - siterx-shorty-backend
         - siterx-ehr-patient-extractor
         - siterx-encryption-service
         - siterx-document-handler
         - siterx-ehr-patient-rpt-upload
      action:
        description: Choose an action to perform
        type: choice
        default: ${{ github.event.inputs.vmRepo }}
        options:
         - Build
         - Deploy
         - Delete
jobs:
  setup:
    env: 
      repo: devops
      branch: dev
    name: setup the environment
    runs-on: ubuntu-latest
    steps:
      - run: echo "helllo $repo  $branch ${{ github.event.inputs.vmRepo }}"
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: technophilnomad/devops
