name: Testing workflow dispatch input

on:
  workflow_dispatch:
    inputs:
      vmRepo:
        description: Choose a source SiteRx Repo to checkout.
        type: choice
        options:
         - FRONTEND
         - siterx-referral-console
         - siterx-annotator
         - siterx-trial-site-console
         - siterx-site-console
         - siterx-super-admin
         - siterx-payments
         - siterx-shorty-console
         - BACKEND
         - siterx-webapp
         - siterx-shorty-backend
         - siterx-ehr-patient-extractor
         - siterx-encryption-service
         - siterx-document-handler
         - siterx-ehr-patient-rpt-upload
      action:
        description: Choose an action to perform
        type: choice
        default: build
        options:
         - Build
         - Deploy
         - Delete
jobs:
  setup:
    env: 
      frontend : '["siterx-referral-console","siterx-annotator","siterx-trial-site-console"]'
      backend : '["siterx-webapp", "siterx-shorty-backend"]'
      repo: devops
      branch: dev
      vmRepo: ${{ github.event.inputs.vmRepo }}
      FrontendRepoName: 'siterx-annotator'
      BackendRepoName: 'siterx-shorty-backend'
      
    name: Conditionally Run
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      #!
      - if: contains(env.frontend, env.vmRepo)
        id: step1
        run: |
          echo $FrontendRepoName is frontend $InpRepoName
          echo "::set-output name=test::hello"
      - if: contains(env.backend, env.vmRepo)
        id: step2
        run: |
          echo $FrontendRepoName is Backend $InpRepoName
          echo "::set-output name=test::world"
      
  check:
    name: output check
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - name: checking the output
        run: |
          echo ${{needs.setup.outputs.output1}}
          echo ${{needs.setup.outputs.output2}}
