name: Call Reusable Demo Workflow

on: [push, workflow_dispatch]

jobs:
  call-reusable-workflow:
    uses: Technophilnomad/Devops/.github/workflows/reusable_demo_workflow.yml@main
    with:
      example-input: 'Hello, world!'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
