name: Reusable Demo Workflow

on:
  workflow_call:
    secrets:
      aws-access-key-id:
        description: AWS Access Key ID
        required: true
      aws-secret-access-key:
        description: AWS Secret Access Key
        required: true
    inputs:
      example-input:
        description: Example input for demonstration
        required: true
        type: string

jobs:
  demo-job:
    runs-on: ubuntu-latest
    name: Run demo job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Input
        run: echo "The input was ${{ inputs.example-input }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: us-east-1

      - name: Demo step
        run: |
          echo "This is a demo step"
          echo "More steps can be added here as needed"
