name: Call Reusable Demo Workflow

on: workflow_dispatch

jobs:
  call-reusable-workflow:
    uses: Technophilnomad/Devops/.github/workflows/reusable_demo_workflow.yml@main
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      example-input: 'Hello, world!'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
