name: Automatic Notify to Slack

on:
  workflow_dispatch:
  
jobs:
  Notify:
    name: Sending Notification to Slack
    runs-on: ubuntu-latest 
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C047XS83PU1\",\"text\":\"Hello world\"}'
