name: Build with slack notify

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  slack-action:
    name: Sending Notification to Slack
    runs-on: ubuntu-latest     
    steps:
      - name: Send build started to slack
        uses: archive/github-actions-slack@master
        id: slack-build-started

        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: C047XS83PU1
          slack-text: |
            :hourglass: Build status: Building...
            Please wait 😁
      - name: Fake build process
        id: fake-build-process
        run: |
          RES=$(curl https://httpbin.org/json -s)
          RES="${RES//'%'/'%25'}"
          RES="${RES//$'\n'/'%0A'}"
          RES="${RES//$'\r'/'%0D'}"
          echo "::set-output name=BUILD_RESULT::$RES"
      - name: Update slack with build result
        uses: archive/github-actions-slack@master
        with:
          slack-function: update-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: C047XS83PU1
          slack-update-message-ts: ${{ fromJson(steps.slack-build-started.outputs.slack-result).response.message.ts }}
          slack-update-message-text: "${{ format('{0}\n\n```{1}```', ':no_entry_sign: Build status: Failed!', steps.fake-build-process.outputs.BUILD_RESULT) }}"
