name: Automatic Notify to Slack

on:
  workflow_dispatch:
  
jobs:
  Notify:
    name: Sending Notification to Slack
    runs-on: ubuntu-latest 
    steps:
      - name: Run command    
        run: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
