name: Initial pipeline

on: 
  workflow_dispatch:
  push:
    branches:
      - "dev"
env: 
  repo: devops
  branch: dev
jobs:
  setup:
    name: setup the environment
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "helllo world" 
    
  Checkout:
    steps:
    - uses: actions/checkout@v3
      with:
        repository : technophilnomad/$repo
        ref: $branch


