name: Initial pipeline

on: 
  workflow_dispatch: {}
  repository_dispatch:
    types: [run-ping]
  push:
    branches:
      - "dev"

jobs:
  setup:
    env: 
      repo: devops
      branch: dev
    name: setup the environment
    runs-on: ubuntu-latest
    steps:
      - run: echo "helllo $repo  $branch"
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: technophilnomad/devops


