name: Initial pipeline

on: 
  workflow_dispatch:
    inputs:
      repoBranch:
        description: Select a branch for the workflow
        type: choice
        options:
        - main
        - dev
        - feature
        default: dev

  push:
    branches:
      - "dev"
env: 
  repo: devops
  branch: dev
jobs:
  setup:
    name: setup the environment
    runs-on: ubuntu-latest
    steps:
      - run: echo "helllo $repo  $branch"
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          repository: technophilnomad/$repo


